version: '3.8'

services:
  # Vector Database with Persistence
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    deploy:
      resources:
        limits:
          memory: 2GB # Dedicated memory for vector indexing

  # Message Broker for Async Tasks
  redis:
    image: redis:alpine
    container_name: redis_broker
    volumes:
      - redis_data:/data

  # Backend API (FastAPI)
  api:
    build: .
    container_name: rag_api
    depends_on:
      - qdrant
      - redis
    env_file: .env
    volumes:
      - ./.env:/app/.env
      - ./data/uploads:/app/data/uploads
      - ./app:/app/app
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 3GB # High memory for reranking and query processing

  # Background Worker (Celery)
  worker:
    build: .
    container_name: ingestion_worker
    command: celery -A app.workers.tasks worker --loglevel=info
    depends_on:
      - redis
      - qdrant
    env_file: .env
    volumes:
      - ./.env:/app/.env
      - ./data/uploads:/app/data/uploads
      - ./app:/app/app
    deploy:
      resources:
        limits:
          memory: 3GB # Memory for PDF parsing and semantic chunking

  # Scheduler (Celery Beat)
  scheduler:
    build: .
    container_name: celery_scheduler
    command: celery -A app.workers.celery_app beat --loglevel=info
    depends_on:
      - redis
    env_file: .env
    volumes:
      - ./.env:/app/.env
      - ./app:/app/app


  # Frontend (Streamlit)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_frontend
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/api/v1
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api

# Persistent storage for your data
volumes:
  qdrant_storage:
  redis_data:
